apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recipe-share

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: recipe-share
